#!/bin/bash

source $SWEIBO_DIR/common

echo "Checking authorization validation..."

response=$("$SWEIBO_MODULE_DIR/oauth2/get_token_info")
if [ -z "$response" ]; then
    echo -e "\e[31mInvalid authorization\e[0m"
    exit 1
fi

user_uid=$(echo "$response" | jq ".uid")
printf "\tUID: %s\n" "$user_uid"
echo -e "\e[32mValid authorization\e[0m"
