#!/bin/bash

source "$SWEIBO_FACILITIES_DIR/common"
source "$SWEIBO_FACILITIES_DIR/presentation"

temp_file=$(mktemp)
vim "$temp_file"
text=$(cat "$temp_file" | sed '$a ---- From sweibo https://github.com/linyinfeng/sweibo')

breakline
echo -e "\e[1m$text\e[0m"
breakline
echo -n "Create status? [y/n] "
read confirm
if [ "$confirm" = "n" ]; then
    exit 1
fi
response=$(echo "$text" | "$SWEIBO_MODULES_DIR/api/statuses/share")
if [ -z "$response" ]; then exit 1; fi
breakline
display_status "$response"
breakline

rm "$temp_file"
