#!/bin/bash

source "$SWEIBO_FACILITIES_DIR/common"
source "$SWEIBO_FACILITIES_DIR/presentation"

comments_file="$SWEIBO_CONFIG_DIR/comments_file"

if [ ! -f "$comments_file" ]; then
    echo -e "\e[31mNo comment viewed\e[0m"
    exit 1
fi
comment_num="$1"
if [ -z "$comment_num" ]; then
    echo -e "\e[31mPlease add status number to the end of the argument list\e[0m"
    exit 1
fi
comment=$(sed "${comment_num}q;d" "$comments_file")
status=$(echo "$comment" | jq -r ".status")
cid=$(echo "$comment" | jq -r ".id")
sid=$(echo "$status" | jq -r ".id")
if [ "$cid" = "null" ]; then
    echo -e "\e[31mNo such comment\e[0m"
    exit 1
fi

breakline
display_status "$status"
breakline
display_comment "$comment"
breakline

echo -n "Start editing comment? [y/n] "
read confirm
if [ "$confirm" = "n" ]; then
    exit 1
fi

temp_file=$(mktemp)
"$EDITOR" "$temp_file"
text=$(cat "$temp_file")

breakline
echo -e "\e[1m$text\e[0m"
breakline
echo -n "Create comment? [y/n] "
read confirm
if [ "$confirm" = "n" ]; then
    exit 1
fi
response=$(echo "$text" | "$SWEIBO_MODULES_DIR/api/comments/reply" -s "$sid" -c "$cid")
if [ -z "$response" ]; then
    echo -e "\e[31mFailed to sent comment\e[0m"
    exit 1
fi
breakline
display_comment "$response"
breakline

rm "$temp_file"
