#!/bin/bash

source $SWEIBO_DIR/common

status_file="$SWEIBO_CONFIG_DIR/timeline_statuses"
refresh="false"

while getopts r FLAG; do
    case $FLAG in
        r) refresh="true";;
        *) :;;
    esac
done

if [ ! -f "$status_file" ]; then refresh="true"; fi

if [ $refresh = "true" ]; then
    response=$("$SWEIBO_MODULE_DIR/statuses/public_timeline")
    if [ -z "$response" ]; then
        echo -e "\e[31mFailed to get timeline, exiting...\e[0m"
        exit 1
    fi
    echo "$response" | jq ".statuses[]" -c > "$status_file"
fi

statuses_count=$(wc -l $status_file | awk '{print $1}')
printf "Statuses count: %d\n"  "$statuses_count"
breakline "\e[32m"

i=1
while (( i <= statuses_count )); do
    sed "${i}q;d" $status_file | cat
    breakline "\e[32m"
    let ++i
done
