#!/bin/bash

response=$("$SWEIBO_MODULES_DIR/api/remind/unread_count")
if [ -z "$response" ]; then exit 1; fi

mention_status=$(echo "$response" | jq -r ".mention_status")
mention_comment=$(echo "$response" | jq -r ".mention_cmt")
other_comment=$(echo "$response" | jq -r ".cmt")

new_comment=$((mention_comment + other_comment))
new_status=$mention_status

echo "New Status:  $new_status"
echo "New comment: $new_comment"