#!/bin/bash

#EXAMPLE
# https://api.weibo.com/oauth2/default.html?code=64efca4a5385c96327f6042883527575
# https://api.weibo.com/oauth2/default.html?error_uri=%2Foauth2%2Fauthorize&error=access_denied&error_description=user%20denied%20your%20request.&error_code=21330

source ./random

CLIENT_ID='2276631549'
CLIENT_SECRET='8dc4d53f11fd526170382c4cfa2a0224'
REDIRECT_URI='https://api.weibo.com/oauth2/default.html'

AUTH_FILE=$1

echo $'To authorize this app, visit: \n'
echo "https://api.weibo.com/oauth2/authorize?client_id=$CLIENT_ID&redirect_uri=$REDIRECT_URI&response_type=code"
echo -n $'\nEnter the response uri: '
read input
CODE=$(echo $input | sed 's/.*?code=\([[:alnum:]]*\).*/\1/' | xargs) # xargs for triming the output
if [ $CODE = $input ]; then echo "Error, can't get authorization code"; exit 1; fi
printf "New code get: %s\n" $CODE
echo "code $CODE" > $AUTH_FILE
echo "Getting access token..."

response=$(curl "https://api.weibo.com/oauth2/access_token" \
        -d "client_id=$CLIENT_ID" \
        -d "client_secret=$CLIENT_SECRET" \
        -d "grant_type=authorization_code" \
        -d "code=$CODE" \
        -d "redirect_uri=$REDIRECT_URI")
printf "Response: "; echo $response

if [ $(echo response | jq ".error") != "null" ]; then
    printf "Error: "; echo $(echo response | jq ".error_description" | tr -d '"');
    exit 1
fi
ACCESS_TOKEN=$(echo $response | jq ".access_token" | tr -d '"')
printf "New access_token get: %s\n" $ACCESS_TOKEN
echo "access_token $ACCESS_TOKEN" >> $AUTH_FILE

