#!/bin/bash

source ./common

echo "Checking authorization validation..."
response=$(curl -s -d "access_token=$ACCESS_TOKEN" 'https://api.weibo.com/oauth2/get_token_info')

echo $response | check_error || exit 1

user_uid=$(echo $response | jq ".uid")
printf "\tUID: %s\n" $user_uid
echo "Valid authorization"