#!/bin/bash

source ./common

echo "Checking authorization validation..."
response=$(curl -d "access_token=$ACCESS_TOKEN" 'https://api.weibo.com/oauth2/get_token_info')

echo $response | check_error

echo $response | jq
