#!/bin/sh

mkdir -p "$HOME/.sweibo"
touch "$HOME/.sweibo/dbus_address"
chmod 600 "$HOME/.sweibo/dbus_address"
env | grep "DBUS_SESSION_BUS_ADDRESS" > "$HOME/.sweibo/dbus_address"
echo 'export DBUS_SESSION_BUS_ADDRESS' >> "$HOME/.sweibo/dbus_address"
