#!/bin/bash

function display_user_brief() {
    local data=$1
    local name=$(echo "$data" | jq -r ".screen_name")
    local id=$(echo "$data" | jq -r ".id")
    echo -en "User: \e[36;1m$name\e[0m"
    local description=$(echo "$data" | jq -r ".description" | tr '\n\r' '  ')
    echo -en "\t$description\n\n"
}

function display_user {
    local data=$1
}

function display_picture {
    local cols=$(tput cols)
    local pic=$1

    local pic_extension_name=$(echo "$pic" | grep -o '\.[[:alpha:]]*$')
    local pic_file_name=$(echo "$pic" | sed 's/.*\/\([[:alnum:]]*\.[[:alpha:]]*\)$/\1/g')
    echo $pic_file_name

    if [ "$pic_extension_name" != ".gif" ]; then
        local pic_width
        let "pic_width = cols / 2"
        local temp_file="$SWEIBO_TEMP_DIR/$pic_file_name"

        if [ ! -f $temp_file ]; then
            curl -s "$pic" -o $temp_file
        fi

        if [ -f "/usr/bin/catimg" ]; then
            catimg -w "$pic_width" "$temp_file"
        elif [ -f "$SWEIBO_DIR/catimg" ]; then
            "$SWEIBO_DIR/catimg" -w "$pic_width" "$temp_file"
        fi
    fi
}

function display_status {
    local data=$1
    local user_data=$(echo "$data" | jq ".user")

    printf "%s\n" $(echo "$data" | jq -r ".id")
    display_user_brief "$user_data" | sed 's/^//g'

    #echo -en "\e[1m"
    # delete U+200B at end of message
    echo -en "$(echo "$data" | jq -r ".text" | sed 's/^/    \\e[1m/g' | sed 's/'$(echo -ne '\u200B')'*$//g')" | sed 's/^/'$extra_lead'/g'
    echo -e "\e[0m"

    local pic=$(echo "$data" | jq -r ".thumbnail_pic")
    local pic_urls=$(echo "$data" | jq -r '.pic_urls[].thumbnail_pic' | sed 's/thumbnail/large/g')

    if [ "$pic" != "null" ]; then
        echo "$pic_urls" | sed 's/^/    Picture: /g'
        display_picture "$pic" | sed 's/^/            /g'
    fi
    echo

    # retweeted_status
    local retweeted_status=$(echo "$data" | jq -r ".retweeted_status")
    if [ -n "$retweeted_status" -a "$retweeted_status" != "null" ]; then
        breakline
        display_status "$retweeted_status"
        breakline
    fi

    local cols=$(tput cols)
    local reposts_count=$(echo "$data" | jq -r ".reposts_count")
    local comments_count=$(echo "$data" | jq -r ".comments_count")
    printf "%${cols}s\n" "Reposts: $reposts_count, Comments: $comments_count"
    local date=$(echo "$data" | jq -r ".created_at")
    printf "%${cols}s\n" "Created at $date"
}

function display_comment {
    cols=$(tput cols)
    local data=$1
    local user_data=$(echo "$data" | jq ".user")
    display_user_brief "$user_data"

    # delete U+200B at end of message
    echo -en "$(echo "$data" | jq -r ".text" | sed 's/^/    \\e[1m/g' | sed 's/'$(echo -ne '\u200B')'*$//g')"
    echo -e "\e[0m"

    local date=$(echo "$data" | jq -r ".created_at")
    printf "\n%${cols}s\n" "Created at $date"
}
