#!/bin/bash

export SWEIBO_DIR
export SWEIBO_MODULE_DIR
export SWEIBO_CONFIG_DIR
export ACCESS_TOKEN

BIN_FILE=$(readlink -f "$0")
SWEIBO_DIR=$(dirname "$BIN_FILE")
SWEIBO_MODULE_DIR="$SWEIBO_DIR/modules"
SWEIBO_CONFIG_DIR="$HOME/.sweibo"
AUTH_FILE="$SWEIBO_CONFIG_DIR/auth"

if [[ ! ( -d $SWEIBO_CONFIG_DIR ) ]]; then
    mkdir "$SWEIBO_CONFIG_DIR"
fi

function print_usage()
{
    echo "Usage: TODO"
}

function clean()
{
    if [ -d "$SWEIBO_CONFIG_DIR" ]; then
        rm -rv "$SWEIBO_CONFIG_DIR"
    else
        echo "Already clean"
    fi
}

function auth()
{
    "$SWEIBO_MODULE_DIR/auth" "$AUTH_FILE"
}

function get_access_token()
{
    if [ -f $AUTH_FILE ]; then
        ACCESS_TOKEN=$(awk '$1=="access_token" {print $2}' $AUTH_FILE)
    fi
    if "$SWEIBO_MODULE_DIR/check"; then
        :
    else
        ACCESS_TOKEN=''
    fi
}

function auth_until_valid()
{
    get_access_token
    while [ -z $ACCESS_TOKEN ];
    do
        echo -e "\e[32mPlease follow the instructions to authorize the tool\e[0m"
        auth
        get_access_token
    done
    printf "Access token loaded: %s\n" $ACCESS_TOKEN
}

function handle_input()
{
    input=$@
    case $(echo $input | awk '{print $1}') in
    q|quit|exit) exit;;
    auth)
        second=$(echo $input | awk '{print $2}')
        if [[ ( -n $second ) && ( $second = "force" ) ]]; then
            rm $AUTH_FILE; ACCESS_TOKEN=""
        fi
        auth_until_valid
        ;;
    '') :;;
    *)
        call=$(echo $input | xargs)
        (eval "$SWEIBO_MODULE_DIR/$call")
        ;;
    esac
}

auth_until_valid

while true;
do
    read -ep '(SWeibo) ' input
    handle_input $input
done
