#!/bin/bash

export CONFIG_DIR="$HOME/.sweibo"
MODULE_DIR="./modules"
AUTH_FILE="$CONFIG_DIR/auth"
export SWEIBO_DIR=$(pwd)
export ACCESS_TOKEN=""
if [[ ! ( -d $CONFIG_DIR ) ]]; then
    mkdir $CONFIG_DIR
fi

function print_usage()
{
    echo "Usage: TODO"
}

function clean()
{
    if [ -d $CONFIG_DIR ]; then
        rm -rv $CONFIG_DIR
    else
        echo "Already clean"
    fi
}

function auth()
{
    ./auth $AUTH_FILE
}

function get_access_token()
{
    if [ -f $AUTH_FILE ]; then
        ACCESS_TOKEN=$(awk '$1=="access_token" {print $2}' $AUTH_FILE)
    fi
    # TODO check the access
}

case $1 in
    clean) clean; exit;;
    auth) auth; exit;;
    *) :;; # Do nothing
esac

function auth_until_valid()
{
    get_access_token
    while [ -z $ACCESS_TOKEN ];
    do
        echo "Invalid authorization, please follow the instructions to authorize the tool"
        auth
        get_access_token
    done
    printf "Access token loaded: %s\n" $ACCESS_TOKEN
}

auth_until_valid

HISTFILE="$SWEIBO_DIR/history"
set -o history
real_history_file="$SWEIBO_DIR/real_history"

EXIT_FLAG=""
while [ -n EXIT_FLAG ];
do
    read -ep '(SWeibo) ' input
    case $(echo $input | awk '{print $1}') in
        q) exit;;
        auth)
            second=$(echo $input | awk '{print $2}')
            if [[ ( -n $second ) && ( $second = "force" ) ]]; then
                rm $AUTH_FILE; ACCESS_TOKEN="";
            fi
            auth_until_valid
            echo $input >> $real_history_file; cp $real_history_file $HISTFILE
            ;;
        '') :;;
        *)
            call=$(echo $input | xargs)
            (eval "$MODULE_DIR/$call")
            echo $input >> $real_history_file; cp $real_history_file $HISTFILE
            ;;
    esac
done
