#!/bin/bash

export SWEIBO_DIR
export SWEIBO_MODULES_DIR
export SWEIBO_CONFIG_DIR
export SWEIBO_FACILITIES_DIR
export SWEIBO_TEMP_DIR
export ACCESS_TOKEN

# Define paths of exported dirs
BIN_FILE=$(readlink -f "$0")
SWEIBO_DIR=$(dirname "$BIN_FILE")
SWEIBO_FACILITIES_DIR="$SWEIBO_DIR/facilities"
SWEIBO_MODULES_DIR="$SWEIBO_DIR/modules"
SWEIBO_CONFIG_DIR="$HOME/.sweibo"
SWEIBO_TEMP_DIR="$SWEIBO_CONFIG_DIR/tmp"

# The file used by modules/auth to store auth info
AUTH_FILE="$SWEIBO_CONFIG_DIR/auth"

if [ ! -d "$SWEIBO_CONFIG_DIR" ]; then
    mkdir "$SWEIBO_CONFIG_DIR"
fi
if [ ! -d "$SWEIBO_TEMP_DIR" ]; then
    mkdir "$SWEIBO_TEMP_DIR"
fi

function get_access_token()
{
    if [ -f $AUTH_FILE ]; then
        ACCESS_TOKEN=$(awk '$1=="access_token" {print $2}' $AUTH_FILE)
    fi
    # If check failed, assign access_token to ''
    "$SWEIBO_MODULES_DIR/check" || ACCESS_TOKEN=''
}

function auth_until_valid()
{
    get_access_token
    while [ -z "$ACCESS_TOKEN" ];
    do
        echo -e "\e[32mPlease follow the instructions to authorize the tool\e[0m"
        "$SWEIBO_MODULES_DIR/auth" "$AUTH_FILE"
        get_access_token
    done
    printf "Access token loaded: %s\n" "$ACCESS_TOKEN"
}

function handle_input()
{
    input=$@
    case $(echo "$input" | awk '{print $1}') in
    q|quit|exit) exit;;
    auth)
        # If second parameter is 'force', remove the existing auth file
        # and access_token
        second=$(echo "$input" | awk '{print $2}')
        if [ "$second" = "force" ]; then
            rm $AUTH_FILE; ACCESS_TOKEN=""
        fi
        auth_until_valid
        ;;
    '') :;;
    *)
        call=$(echo "$input" | xargs)
        module_file_path="$SWEIBO_MODULES_DIR/$(echo "$call" | awk '{print $1}')"
        if [ -f $module_file_path ]; then
            (eval "$SWEIBO_MODULES_DIR/$call")
        else
            echo -e "\e[31mModule not found\e[0m"
        fi
        ;;
    esac
}

if [ -z "$1" ]; then
    handle_input "help"
elif [ "$1" = "shell" ]; then
    auth_until_valid

    #wordlist=$(find "$SWEIBO_MODULES_DIR" -type f -name "*" | sed 's/^.//g' | sed 's/^\///g')
    #complete -W "$(echo "$comp" | xargs)" -E
    cd "$SWEIBO_MODULES_DIR" # for compeletion
    #PWD="$SWEIBO_MODULES_DIR" 

    while true; do
        read -e -p '(SWeibo) ' input
        handle_input $input
    done
else
    # Do not check
    if [ -f "$AUTH_FILE" ]; then
        ACCESS_TOKEN=$(awk '$1=="access_token" {print $2}' $AUTH_FILE)
    fi
    handle_input $@
fi
