#!/bin/bash

source "$SWEIBO_FACILITY_DIR/common"

params="access_token=$ACCESS_TOKEN"
test=false

while getopts t FLAG; do
    case $FLAG in
        t) test=true;;
        *) :;;
    esac
done

status=$(cat)

if [ $test = true ]; then
    echo 'curl -s "https://api.weibo.com/2/statuses/share.json" -d "'$params'" --data-urlencode "status='$status'"'
    exit 1
fi

response=$(curl -s "https://api.weibo.com/2/statuses/share.json" -d "$params" --data-urlencode "status=$status")

echo "$response" | check_error || exit 1
echo "$response"
