#!/bin/bash

function display_user_brief() {
    local data=$1
    local name=$(echo "$data" | jq -r ".screen_name")
    local id=$(echo "$data" | jq -r ".id")
    echo -en "User: \e[36;1m$name ($id)\e[0m"
    local description=$(echo "$data" | jq -r ".description" | tr '\n\r' '  ')
    echo -en "\t$description\n\n"
}

function display_user {
    local data=$1
    local name=$(echo "$data" | jq -r ".screen_name")
    echo -en "User: \e[36;1m$name\e[0m\n"
    local description=$(echo "$data" | jq -r ".description" | tr '\n\r' '  ')
    echo -en "Description: \e[36;1m$description\e[0m\n"
    local location=$(echo "$data" | jq -r ".location")
    echo -en "Location: \e[36;1m$location\e[0m\n"
    local followers_count=$(echo "$data" | jq -r ".followers_count")
    echo -en "Followers_count: \e[36;1m$followers_count\e[0m\n"
    local friends_count=$(echo "$data" | jq -r ".friends_count")
    echo -en "Friends_count: \e[36;1m$friends_count\e[0m\n"
    local statuses_count=$(echo "$data" | jq -r ".statuses_count")
    echo -en "Statuses_count: \e[36;1m$statuses_count\e[0m\n"
}

function display_picture {
    local cols=$(tput cols)
    local pic=$1

    local pic_extension_name=$(echo "$pic" | grep -o '\.[[:alpha:]]*$')
    local pic_file_name=$(echo "$pic" | sed 's/.*\/\([[:alnum:]]*\.[[:alpha:]]*\)$/\1/g')
    

    if [ "$pic_extension_name" != ".gif" ]; then
        local pic_width
        let "pic_width = cols / 2"
        local temp_file="$SWEIBO_TEMP_DIR/$pic_file_name"

        if [ ! -f $temp_file ]; then
            curl -s "$pic" -o $temp_file
        fi

        if [ -f "/usr/bin/catimg" ]; then
            catimg -w "$pic_width" "$temp_file"
        elif [ -f "$SWEIBO_DIR/catimg" ]; then
            "$SWEIBO_DIR/catimg" -w "$pic_width" "$temp_file"
        fi
        
        echo $pic_file_name
    fi
}

function display_status {
    local data=$1
    local user_data=$(echo "$data" | jq ".user")


    id=$(echo "$data" | jq -r ".id")
    uid=$(echo "$user_data" | jq -r ".id")
    printf "http://api.weibo.com/2/statuses/go?access_token=%s&id=%s&uid=%s\n" "$ACCESS_TOKEN" "$id" "$uid"
    display_user_brief "$user_data" | sed 's/^//g'

    #echo -en "\e[1m"
    # delete U+200B at end of message
    echo -en "$(echo "$data" | jq -r ".text" | sed 's/^/    \\e[1m/g' | sed 's/'$(echo -ne '\u200B')'*$//g')" | sed 's/^/'$extra_lead'/g'
    echo -e "\e[0m"

    local pic=$(echo "$data" | jq -r ".thumbnail_pic")
    local pic_urls_raw=$(echo "$data" | jq -r '.pic_urls')
    local pic_ids_raw=$(echo "$data" | jq -r '.pic_ids')
    if [ "$pic_urls_raw" != "null" ]; then
        local pic_urls=$(echo "$pic_urls_raw" | jq -r '.[].thumbnail_pic' | sed 's/thumbnail/large/g')
    elif [ "$pic_ids_raw" != "null" ]; then
        local pic_urls=$(echo "$pic_ids_raw" | jq -r '.[]' | sed 's/^/http:\/\/wx1.sinaimg.cn\/large\//g')
    fi

    if [ "$pic" != "null" ]; then
        echo "$pic_urls" | sed 's/^/    Picture: /g'
        display_picture "$pic" | sed 's/^/            /g'
    fi
    echo

    # retweeted_status
    local retweeted_status=$(echo "$data" | jq -r ".retweeted_status")
    if [ -n "$retweeted_status" -a "$retweeted_status" != "null" ]; then
        breakline "" "."
        echo -en "\e[1m[Retweet] \e[0m"
        display_status "$retweeted_status"
        breakline "" "."
    fi

    local cols=$(tput cols)
    local reposts_count=$(echo "$data" | jq -r ".reposts_count")
    local comments_count=$(echo "$data" | jq -r ".comments_count")
    printf "%${cols}s\n" "Reposts: $reposts_count, Comments: $comments_count"
    local date=$(echo "$data" | jq -r ".created_at")
    printf "%${cols}s\n" "Created at $date"
}

function display_comment {
    cols=$(tput cols)
    local data=$1
    local user_data=$(echo "$data" | jq ".user")
    display_user_brief "$user_data"

    # delete U+200B at end of message
    echo -en "$(echo "$data" | jq -r ".text" | sed 's/^/    \\e[1m/g' | sed 's/'$(echo -ne '\u200B')'*$//g')"
    echo -e "\e[0m"

    local date=$(echo "$data" | jq -r ".created_at")
    printf "\n%${cols}s\n" "Created at $date"
}

# breakline "$HEAD" "$CHAR" "$END"
function breakline() {
    echo -en "$1"

    local cols=$(tput cols)

    local c="-"
    if [ -n "$2" ]; then
        c="$2"
    fi

    local i=0
    while (( i < cols )); do
        echo -n "$c"
        let ++i
    done

    if [ -n "$3" ]; then
        echo -e "$3"
    else
        echo -e "\e[0m"
    fi
}
