#!/bin/bash

source $SWEIBO_DIR/common

params="access_token=$ACCESS_TOKEN"
test=false

while getopts t FLAG; do
    case $FLAG in
        t) test=true;;
        *) :;;
    esac
done

if [ "$test" = "true" ]; then
    echo "curl -s \"https://api.weibo.com/2/account/rate_limit_status.json\" -d \"$params\""
    exit 1
fi

response=$(curl -s "https://api.weibo.com/2/account/rate_limit_status.json" -d "$params")

echo "$response" | check_error || exit 1
echo "$response"
