#!/bin/bash

source "$SWEIBO_FACILITY_DIR/common"

params="access_token=$ACCESS_TOKEN"
test=false

while getopts i:t FLAG; do
    case $FLAG in
        i) params="$params&id=$OPTARG";;    # id
        t) test=true;;
        *) :;;
    esac
done

comment=$(cat)

if [ $test = true ]; then
    echo 'curl -s "https://api.weibo.com/2/comments/create.json" -d "'$params'" --data-urlencode "comment='$comment'"'
    exit 1
fi

response=$(curl -s "https://api.weibo.com/2/comments/create.json" -d "$params" --data-urlencode "comment=$comment")

echo "$response" | check_error || exit 1
echo "$response"
