#!/bin/bash

source "$SWEIBO_FACILITIES_DIR/common"

params="access_token=$ACCESS_TOKEN"
test=false

while getopts c:s:t FLAG; do
    case $FLAG in
        c) params="$params&cid=$OPTARG";; # comment id
        s) params="$params&id=$OPTARG";;  # status id
        t) test=true;;
        *) :;;
    esac
done

comment=$(cat)

if [ $test = true ]; then
    echo 'curl -s "https://api.weibo.com/2/comments/reply.json" -d "'$params'" --data-urlencode "comment='$comment'"'
    exit 1
fi

response=$(curl -s "https://api.weibo.com/2/comments/reply.json" -d "$params" --data-urlencode "comment=$comment")

echo "$response" | check_error || exit 1
echo "$response"
