#!/bin/bash

source "$SWEIBO_FACILITIES_DIR/common"

params="access_token=$ACCESS_TOKEN&uid=$USER_ID&unread_message=1"
test=false

while getopts t FLAG; do
    case $FLAG in
        t) test=true;;
        *) :;;
    esac
done

if [ "$test" = "true" ]; then
    echo "curl -s \"https://api.weibo.com/2/remind/unread_count.json?$params\""
    exit 1
fi

response=$(curl -s "https://api.weibo.com/2/remind/unread_count.json?$params")

echo "$response" | check_error || exit 1
echo "$response"
